apiVersion: apps/v1
kind: Deployment
metadata:
  name: devop-app-deployment
  labels:
    app: react-app
spec:
  replicas: 2 
  selector:
    matchLabels:
      app: devop-app
  template:
    metadata:
      labels:
        app: devop-app
    spec:
      containers:
      - name: devop-app
        image: us.icr.io/devops-arf/devop-app:latest 
        ports:
        - containerPort: 3000  
       
---
apiVersion: v1
kind: Service
metadata:
  name: devop-app-service
spec:
  selector:
    app: devop-app
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000  
  type: LoadBalancer  
