apiVersion: v1
kind: Service
metadata:
  name: devop-app-service
spec:
  selector:
    app: devop-app
  ports:
    - protocol: TCP
      port: 80         
      targetPort: 3000  
  type: LoadBalancer  
